#!/bin/bash

echo "Railway Database Port Forwarding Setup"
echo "======================================"
echo ""
echo "The .railway.internal domains are only accessible from within Railway's network."
echo "To test the databases locally, you need to use Railway's port forwarding."
echo ""
echo "Run these commands in separate terminal windows:"
echo ""
echo "1. Forward PostgreSQL (port 5432):"
echo "   railway run --service postgres -- railway port-forward 5432"
echo ""
echo "2. Forward Redis (port 6379):"
echo "   railway run --service redis -- railway port-forward 6379"
echo ""
echo "Then update your backend/.env to use localhost URLs for local testing:"
echo "   DATABASE_URL=postgresql://postgres:nVytOSmJkCuVHifJsZoMFwsuEgJZVrvE@localhost:5432/railway"
echo "   REDIS_URL=redis://default:WLVdmieztrGHBKFukRtIsFUrESmWUdSJ@localhost:6379"
echo ""
echo "Note: The Railway production URLs will work automatically when deployed to Railway."
