# Railway.app configuration for InventorySync Production Deployment

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Number of replicas - start with 2 for high availability
numReplicas = 2

# Auto-scaling configuration
minReplicas = 2
maxReplicas = 10

# CPU-based auto-scaling (scale up at 70% CPU usage)
[deploy.scaling]
enabled = true
target = "cpu"
min = 2
max = 10
targetCPUPercent = 70

# Health check configuration
[deploy.healthcheck]
path = "/health"
port = 8000
method = "GET"
timeout = 30
interval = 30
initialDelaySeconds = 10
successThreshold = 1
failureThreshold = 3

# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Resource limits
[deploy.resources]
cpu = "1"
memory = "2Gi"

# Request minimum resources
[deploy.resources.requests]
cpu = "500m"
memory = "1Gi"

# Deployment strategy for zero-downtime deployments
[deploy.strategy]
type = "RollingUpdate"
maxSurge = "25%"
maxUnavailable = "0%"

# Rollback configuration
[deploy.rollback]
enabled = true
# Automatically rollback if health checks fail
automaticRollbackOnFailure = true
# Keep last 5 successful deployments for rollback
revisionsHistoryLimit = 5

# Environment-specific settings
[environments.production]
# Production domain configuration
domain = "api.inventorysync.app"

# SSL/TLS configuration
[environments.production.ssl]
enabled = true
redirect = true

# Production environment variables (reference Railway secrets)
[environments.production.variables]
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
WORKERS = "4"
WORKER_CONNECTIONS = "1000"
DATABASE_POOL_SIZE = "20"
DATABASE_POOL_MAX_OVERFLOW = "40"
ENABLE_API_DOCS = "false"
ENABLE_SWAGGER_UI = "false"

# Monitoring and observability
[observability]
# Enable Railway's built-in metrics
metrics = true
# Enable structured logging
structuredLogs = true
# Log level
logLevel = "info"

# Service dependencies
[services]
# Ensure database is available before starting
depends_on = ["postgres", "redis"]

# Lifecycle hooks
[lifecycle]
# Pre-stop hook to gracefully shutdown
preStop = "kill -SIGTERM 1 && sleep 15"

# Post-start hook to warm up the application
postStart = "curl -f http://localhost:8000/health || exit 1"
