global:
  resolve_timeout: 5m
  smtp_from: 'alerts@inventorysync.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: '${ALERT_EMAIL_USERNAME}'
  smtp_auth_password: '${ALERT_EMAIL_PASSWORD}'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical'
      continue: true
    - match:
        severity: warning
      receiver: 'warning'
    - match:
        team: database
      receiver: 'database-team'
    - match:
        team: business
      receiver: 'business-team'

receivers:
  - name: 'default'
    email_configs:
      - to: 'dev-team@inventorysync.com'
        send_resolved: true
        
  - name: 'critical'
    email_configs:
      - to: 'oncall@inventorysync.com'
        send_resolved: true
        headers:
          Subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\nSeverity: {{ .Labels.severity }}{{ end }}'
        send_resolved: true
        username: 'InventorySync Alerts'
        icon_emoji: ':warning:'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        
  - name: 'warning'
    email_configs:
      - to: 'dev-team@inventorysync.com'
        send_resolved: true
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#alerts-warning'
        title: 'Warning: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true
        username: 'InventorySync Alerts'
        icon_emoji: ':warning:'
        color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
        
  - name: 'database-team'
    email_configs:
      - to: 'database-team@inventorysync.com'
        send_resolved: true
        
  - name: 'business-team'
    email_configs:
      - to: 'business-analytics@inventorysync.com'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
