global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'inventorysync-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape InventorySync API
  - job_name: 'inventorysync-api'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For local development
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Scrape InventorySync API (production)
  - job_name: 'inventorysync-api-prod'
    static_configs:
      - targets: ['${INVENTORYSYNC_API_URL}']  # Will be replaced with actual URL
    metrics_path: '/metrics'
    scrape_interval: 15s
    scheme: 'https'
    
  # Scrape Redis metrics if using Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    
  # Scrape PostgreSQL metrics if using postgres exporter  
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
