{
 "title": "InventorySync Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Response Time (Average)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inventorysync_http_request_duration_seconds_sum[5m])) / sum(rate(inventorysync_http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Successful Syncs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inventorysync_sync_operations_total{status=\"successful\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sync Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inventorysync_sync_queue_size)",
     "legendFormat": "Queue Size"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inventorysync_http_requests_total{status=~\"5..\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}